-- ============================================================
-- NYC Yellow Taxi Trip Data Analysis
-- Platform: Apache Hive on Hadoop (CloudXLab)
-- Dataset:  yellow_tripdata_2015-01-06.csv (10,000 records)
-- ============================================================


-- ============================================================
-- STEP 0: SETUP - Create Database, Table, and Load Data
-- ============================================================

-- 0.1 Create and select database
CREATE DATABASE IF NOT EXISTS taxi_analysis;
USE taxi_analysis;

-- 0.2 Create table with provided DDL
CREATE TABLE IF NOT EXISTS taxidata (
    vendor_id           STRING,
    pickup_datetime     STRING,
    dropoff_datetime    STRING,
    passenger_count     INT,
    trip_distance       DECIMAL(9,6),
    pickup_longitude    DECIMAL(9,6),
    pickup_latitude     DECIMAL(9,6),
    rate_code           INT,
    store_and_fwd_flag  STRING,
    dropoff_longitude   DECIMAL(9,6),
    dropoff_latitude    DECIMAL(9,6),
    payment_type        STRING,
    fare_amount         DECIMAL(9,6),
    extra               DECIMAL(9,6),
    mta_tax             DECIMAL(9,6),
    tip_amount          DECIMAL(9,6),
    tolls_amount        DECIMAL(9,6),
    total_amount        DECIMAL(9,6),
    trip_time_in_secs   INT
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
TBLPROPERTIES ("skip.header.line.count"="1");

-- 0.3 Load data from CSV
--     First upload CSV to HDFS: hadoop fs -put yellow_tripdata_2015-01-06.csv /user/root/
LOAD DATA INPATH '/user/root/yellow_tripdata_2015-01-06.csv'
INTO TABLE taxidata;

-- 0.4 Verify data loaded correctly
SELECT * FROM taxidata LIMIT 10;

DESCRIBE taxidata;

SELECT COUNT(*) FROM taxidata;


-- ============================================================
-- QUESTION 1: Total number of trips (equal to number of rows)
-- Expected Result: 10000
-- ============================================================

SELECT COUNT(*) AS total_trips
FROM taxidata;


-- ============================================================
-- QUESTION 2: Total revenue generated by all trips
-- Revenue column: total_amount
-- Expected Result: ~160546.81
-- ============================================================

SELECT ROUND(SUM(total_amount), 2) AS total_revenue
FROM taxidata;


-- ============================================================
-- QUESTION 2a: What fraction of total revenue is paid as tolls?
-- Toll column: tolls_amount
-- Expected Result: ~1.56%
-- ============================================================

SELECT
    ROUND(SUM(tolls_amount), 2)                                AS total_tolls,
    ROUND(SUM(total_amount), 2)                                AS total_revenue,
    ROUND(SUM(tolls_amount) / SUM(total_amount) * 100, 2)     AS toll_fraction_pct
FROM taxidata;


-- ============================================================
-- QUESTION 2b: What fraction of total revenue is driver tips?
-- Tip column: tip_amount
-- Expected Result: ~10.79%
-- ============================================================

SELECT
    ROUND(SUM(tip_amount), 2)                                  AS total_tips,
    ROUND(SUM(total_amount), 2)                                AS total_revenue,
    ROUND(SUM(tip_amount) / SUM(total_amount) * 100, 2)       AS tip_fraction_pct
FROM taxidata;


-- ============================================================
-- QUESTION 3: Average trip amount
-- Expected Result: ~16.05
-- ============================================================

SELECT ROUND(AVG(total_amount), 2) AS avg_trip_amount
FROM taxidata;


-- ============================================================
-- QUESTION 4: Average trip distance
-- Distance column: trip_distance
-- Expected Result: ~3.25
-- ============================================================

SELECT ROUND(AVG(trip_distance), 2) AS avg_trip_distance
FROM taxidata;


-- ============================================================
-- QUESTION 5: How many different payment types are used?
-- Expected Result: 4 (types: 1, 2, 3, 4)
-- ============================================================

SELECT COUNT(DISTINCT payment_type) AS distinct_payment_types
FROM taxidata;

-- Show the distinct payment types
-- 1 = Credit card, 2 = Cash, 3 = No charge, 4 = Dispute
SELECT DISTINCT payment_type
FROM taxidata
ORDER BY payment_type;


-- ============================================================
-- QUESTION 6: For each payment type, display:
--   - Average fare generated (fare_amount)
--   - Average tip (tip_amount)
--   - Average tax (mta_tax)
--
-- Expected Results:
--   Type 1 (Credit card): avg_fare=13.56, avg_tip=2.70, avg_tax=0.50
--   Type 2 (Cash):        avg_fare=11.39, avg_tip=0.00, avg_tax=0.50
--   Type 3 (No charge):   avg_fare=13.21, avg_tip=0.00, avg_tax=0.42
--   Type 4 (Dispute):     avg_fare=12.22, avg_tip=0.00, avg_tax=0.50
-- ============================================================

SELECT
    payment_type,
    ROUND(AVG(fare_amount), 2)  AS avg_fare,
    ROUND(AVG(tip_amount), 2)   AS avg_tip,
    ROUND(AVG(mta_tax), 2)      AS avg_tax
FROM taxidata
GROUP BY payment_type
ORDER BY payment_type;


-- ============================================================
-- QUESTION 7: On average, which hour of the day generates
--             the highest revenue?
--
-- Approach: Extract hour from pickup_datetime using
--           HOUR() function, then compute AVG(total_amount)
--           per hour and sort descending.
--
-- Expected Result: Hour 22 (10 PM) with avg revenue ~16.24
-- ============================================================

SELECT
    HOUR(pickup_datetime)                   AS pickup_hour,
    ROUND(AVG(total_amount), 2)             AS avg_revenue
FROM taxidata
GROUP BY HOUR(pickup_datetime)
ORDER BY avg_revenue DESC;

-- To show only the single highest-revenue hour:
SELECT
    pickup_hour,
    avg_revenue
FROM (
    SELECT
        HOUR(pickup_datetime)               AS pickup_hour,
        ROUND(AVG(total_amount), 2)         AS avg_revenue
    FROM taxidata
    GROUP BY HOUR(pickup_datetime)
) hourly_revenue
ORDER BY avg_revenue DESC
LIMIT 1;


-- ============================================================
-- END OF ANALYSIS
-- ============================================================
